version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    container_name: library
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./library_sql:/data/sql
    ports:
      - "5432:5432"
