version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    container_name: library
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql:/sql
      - ./configs:/var/lib/postgresql/data
    ports:
      - "5432:5432"
